version: "3.7"
services:
  db:
    image: postgres:13-alpine
    container_name: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_USER: sungjin
      POSTGRES_DB: blog

