version: '3.7'

services:
  testHost:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg/database:/var/lib/postgresql/data
      - ./pg/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_USER: testUser
      POSTGRES_DATABASE: testDatabase
      POSTGRES_PASSWORD: testPassword

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - testHost
    environment:
      EXPRESS_DB_USER: testUser
      EXPRESS_DB_PASSWORD: testPassword
      EXPRESS_DB_DATABASE: testDatabase
      EXPRESS_DB_HOST: testHost
      PORT: 4000